service: move-files

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::move-files-bucket/*"

functions:
  post:
    handler: handler.post
    events:
      - http:
          path: index/post
          method: any
  auth:
    handler: handler.auth
    events:
      - http:
          path: index/auth
          method: any

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: move-files-bucket
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
